services:
  - type: web
    name: pomodoro-timer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-auth.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
